---
title: "Prob"
author: "rhadoop"
date: "2019년 3월 13일"
output: 
  word_document: default
  html_notebook: default
  html_document: default
  pdf_notebook: default
  pdf_document: 
    latex_engine: xelatex
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```



## 문제1. ggplot2의 midwest 데이터의 특성을 파악하세요
```{r}
library(ggplot2)
library(dplyr)
df_midwest <-as.data.frame(ggplot2::midwest)
head(df_midwest,10)
tail(df_midwest,10)
dim(df_midwest)
str(df_midwest)
View(df_midwest)
summary(df_midwest)
```





## 문제2. poptotal -> total, popasian -> asian 으로 변수명을 수정하세요
```{r}
rename(df_midwest, total=poptotal, asian=popasian) -> df_midwest
names(df_midwest)
```





## 문제3. 전체 인구 대비 아시아 인구 백분율 파생변수를 만들고 히스토그램을 만드세요
```{r}
df_midwest$asian_ratio <- (df_midwest$asian/df_midwest$total)*100
hist(df_midwest$asian_ratio)
```




## 문제4. 아시아 인구 백분율 전체 평균 초과시 large, 그 외에는 small을 부여하세요
```{r}
df_midwest$asian_pop <- ifelse(df_midwest$asian_ratio > mean(df_midwest$asian_ratio), "large",'small')
head(df_midwest[,c(1,2,29,30)],20)
```




## 문제5. large, small 빈도표와 빈도 막대 그래프를 만드세요

```{r}
table(df_midwest$asian_pop)
qplot(df_midwest$asian_pop)
```



